### ISSUE TITLE
Doesn't Run on 1.15.2 Paper

### ISSUE THREAD

**Issue by ghost** [games647/CommandForward#2]
```
# Startup Message
[16:14:15 WARN]: Legacy plugin CommandForward v0.1 does not specify an api-version.
[16:14:17 INFO]: [CommandForward] Loading CommandForward v0.1
[16:14:41 INFO]: [CommandForward] Enabling CommandForward v0.1*
[16:14:41 ERROR]: Error occurred while enabling CommandForward v0.1 (Is it up to date?)
java.lang.IllegalArgumentException: Channel must contain : separator (attempted to use CommandForward)
	at com.github.games647.commandforward.bukkit.CommandForwardBukkit.onEnable(CommandForwardBukkit.java:21) ~[?:?]
[16:14:41 INFO]: [CommandForward] Disabling CommandForward v0.1

# Attempting to run /forward
[16:10:25 ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'forward' in plugin CommandForward v0.1 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[patched_1.15.2.jar:git-Paper-77]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-77]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:740) ~[patched_1.15.2.jar:git-Paper-77]
        at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1820) ~[patched_1.15.2.jar:git-Paper-77]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1628) ~[patched_1.15.2.jar:git-Paper-77]
        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Paper-77]
        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Paper-77]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-77]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-77]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-77]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-77]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-77]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Paper-77]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[patched_1.15.2.jar:git-Paper-77]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-77]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1102) ~[patched_1.15.2.jar:git-Paper-77]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-77]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]
```

**Comment by ghost** [comment]
nvm, the github version has the colon that the plugin needs to work. I only realized that by looking into the source code.

**Comment by ghost** [comment]
well, there are more errors (most notable the infamous NullPointerException). Imma see if I can debug it as I really want to be able to execute bungee commands from both command blocks and chestcommands.
