### ISSUE TITLE
Error while enabling 

### ISSUE THREAD

**Issue by stonegray** [games647/CommandForward#5]
I'm getting the following error when enabling the server on Tuinity 1.15.2. 

Error:
```
[20:45:09 INFO]: [CommandForward] Enabling CommandForward v0.1*
[20:45:09 ERROR]: Error occurred while enabling CommandForward v0.1 (Is it up to date?)
java.lang.IllegalArgumentException: Channel must contain : separator (attempted to use CommandForward)
at org.bukkit.plugin.messaging.StandardMessenger.validateAndCorrectChannel(StandardMessenger.java:503) ~[patched_1.15.2.jar:git-Tuinity-"64e46c6"]
at org.bukkit.plugin.messaging.StandardMessenger.registerOutgoingPluginChannel(StandardMessenger.java:183) ~[patched_1.15.2.jar:git-Tuinity-"64e46c6"]
at com.github.games647.commandforward.bukkit.CommandForwardBukkit.onEnable(CommandForwardBukkit.java:21) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Tuinity-"64e46c6"]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:364) ~[patched_1.15.2.jar:git-Tuinity-"64e46c6"]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Tuinity-"64e46c6"]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472) ~[patched_1.15.2.jar:git-Tuinity-"64e46c6"]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386) ~[patched_1.15.2.jar:git-Tuinity-"64e46c6"]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Tuinity-"64e46c6"]
at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:299) ~[patched_1.15.2.jar:git-Tuinity-"64e46c6"]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:897) ~[patched_1.15.2.jar:git-Tuinity-"64e46c6"]
at java.lang.Thread.run(Thread.java:834) [?:?]
[20:45:09 INFO]: [CommandForward] Disabling CommandForward v0.1
```

Enviroment:
Server: `Tuinity version git-Tuinity-"64e46c6" (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)`
Java: `openjdk 18.9 "11.0.6" 2020-01-144`
OS: `Ubuntu, Linux 4.15.0-99-generic (amd64)`

**Comment by stonegray** [comment]
Doesn't reproduce when built from source targeting `1.15.2`, seems to only happen when downloading from Spigot.
